### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/easypar#3]
```custom_SBATCH = default_SBATCH_config(W = '12:00')```
`W` is not a param?

**Comment by caravagn** [comment]
I changed the manual to avoid crashing the build. I think we should document the vignette as well (and maybe add to the description the names of the supported clusters)

**Comment by Militeee** [comment]
I agree, but we should first include PBS and conform LSF and SLURM scripts. 
Gonna open separate issues for each.
