### ISSUE TITLE
Adding PBS support

### ISSUE THREAD

**Issue by Militeee** [caravagnalab/easypar#4]
Ideally should be similar to the SLURM implementation

**Comment by caravagn** [comment]
AMazing, coordinate with @nicola-calonaci

**Comment by nicola-calonaci** [comment]
Should be solved, see last commits. (In R folder, default_PBSpro_config.R and pbspro.R)

**Comment by caravagn** [comment]
Good. Please update the documentation as well before closing the issue. This means both the markdown vignette and the Roxygen.

**Comment by nicola-calonaci** [comment]
I pushed the .Rd files in man folder and the .Rmd vignette in vignettes folder. Not sure how to update the references for the new function.

**Comment by Militeee** [comment]
@nicola-calonaci please check the example on the default QSUB list, apparently it does not work

**Comment by nicola-calonaci** [comment]
Thanks! Should be ok now.
